# presidentma <maliang.pr@qq.com>
name: command-cb
version: '1.0.3'
summary: Group commands,history commands,command short tags,Visually manage
description: |
  * 这是一款管理集工具，有了它，您可以方便的分组、管理和运行您常用的命令，它支持shell和图形两种运行模式。
  * This is a command batch tool.You can use it through the shell and the interface,and 
  it allows you to more easily manage common commands, manage and run.
  * --功能----------------------------
  * 命令分组
  * 为命令设置短标签
  * 通过短标签运行命令
  * 可视化操作等。
  * --FUNCTION------------------------
  * Group commands
  * Set up tag for commands
  * run command through the tag
  * Visually manage groups and commands
  * and so on.

grade: stable 
confinement: strict
apps:
  command-cb:
    command: cb
    environment: 
      {LANGUAGE: zh_CN.UTF-8,LC_ALL: zh_CN.UTF-8,LANG: zh_CN.UTF-8,DISPLAY: 0}
    plugs:
      [home]
parts:
  cb:
    source: .
    plugin: make
    build-packages:
      - pkg-config
      - libncursesw5-dev
      - libc-bin
    override-build: |
      make
      cp -p cb $SNAPCRAFT_PART_INSTALL/cb
